[package]
name = "wfcalc"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_float_eq = "1.1.4"
reqwest = { version = "0.12.15", features = ["blocking", "json"]}
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
